Flowers_web/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Flowers_web.Models;

namespace Flowers_web.Controllers
{
    public class AuthorizationController : Controller
    {
        private flowersEntities1 db = new flowersEntities1();

        // GET: Authorization
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Group);
            return View(users.ToList());
        }

        // GET: Authorization/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Authorization/Create
        public ActionResult Create()
        {
            ViewBag.User_of_Group = new SelectList(db.Groups, "ID", "Name_Group");
            return View();
        }

        // POST: Authorization/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "User_ID,User_Name,User_Pass,User_Status,User_of_Group")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User_of_Group = new SelectList(db.Groups, "ID", "Name_Group", user.User_of_Group);
            return View(user);
        }

        // GET: Authorization/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.User_of_Group = new SelectList(db.Groups, "ID", "Name_Group", user.User_of_Group);
            return View(user);
        }

        // POST: Authorization/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "User_ID,User_Name,User_Pass,User_Status,User_of_Group")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User_of_Group = new SelectList(db.Groups, "ID", "Name_Group", user.User_of_Group);
            return View(user);
        }

        // GET: Authorization/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Authorization/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string User, string Pass)
        {
            if (string.IsNullOrEmpty(User) || string.IsNullOrEmpty(Pass))
            {
                return View();
            }
            var user = db.Users.FirstOrDefault(d => d.User_Name.Equals(User) && d.User_Pass.Equals(Pass));
            if (user == null)
            {
                return View();
            }

            if (user.Group.Name_Group.Equals(Role.Manager.ToString()))
            {
                string userName = user.User_Name;
                Response.SetCookie(CreateCookie(userName));
                return this.RedirectToAction("Index", "Manager");
            }
           else if (user.Group.Name_Group.Equals(Role.CallCenter.ToString()))
            {
                string userName = user.User_Name;
                Response.SetCookie(CreateCookie(userName));
                return this.RedirectToAction("Index", "CallCenter");
            }
            return View();
        }
        private HttpCookie CreateCookie(string value)
        {
            HttpCookie CookiesFlowers = new HttpCookie("FlowersCookie")
            {
                Value = value,
                Expires = DateTime.Now.AddDays(3)
            };
            return CookiesFlowers;
        }
    }

    enum Role
    {
        Manager = 1,
        CallCenter = 2,
        User = 3,
        Admin = 4
    }
}

Flowers_web/Views/Authorization/Create.cshtml
@model Flowers_web.Models.User

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.User_Status)
                    @Html.ValidationMessageFor(model => model.User_Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_of_Group, "User_of_Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("User_of_Group", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User_of_Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Flowers_web/Views/Authorization/Delete.cshtml
@model Flowers_web.Models.User

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group.Name_Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name_Group)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Flowers_web/Views/Authorization/Details.cshtml
@model Flowers_web.Models.User

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group.Name_Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name_Group)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.User_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Flowers_web/Views/Authorization/Edit.cshtml
@model Flowers_web.Models.User

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.User_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.User_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User_Pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User_Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.User_Status)
                    @Html.ValidationMessageFor(model => model.User_Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User_of_Group, "User_of_Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("User_of_Group", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.User_of_Group, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Flowers_web/Views/Authorization/Index.cshtml
@model IEnumerable<Flowers_web.Models.User>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User_Pass)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User_Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Group.Name_Group)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User_Pass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User_Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Group.Name_Group)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.User_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.User_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.User_ID })
        </td>
    </tr>
}

</table>

Flowers_web/Views/Authorization/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using(Html.BeginForm("Login", "Authorization", FormMethod.Post))
{
    @*<input type="hidden" value="@ViewBag.BookId" name="BookId" />*@
    <table>
        <tr><td><p>User:</p></td>
            <td>
                @*@Html.TextBox("Person", "User:")*@
                <input type="text" name="User" value="Yura" />

            </td></tr>
        <tr><td><p>Password :</p></td>
            <td>
                <input type="password" name="Pass" value="123"
                       />
            </td></tr>
        <tr><td><input type="submit" value="Send" /> </td>
            <td></td></tr>
    </table>
}