Flowers_web/Models/Delivery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Flowers_web.Models
{
    public class Delivery
    {
        flowersEntities1 db;
        List<Order_Del> OrderList { get; set; }
        static Delivery Delivery2 { get; set; }
        protected Delivery()
        {
            db = new flowersEntities1();
            OrderList = new List<Order_Del>();
        }

        public static Delivery Instance()
        {
            if (Delivery2 == null)
            {
                Delivery2=new Delivery();
                return Delivery2;
            }
            else
            {
                return Delivery2;
            }
        }

        public List<Order_Del> GetOrderList(string searching)
        {
            DateTime date;
            DateTime.TryParse(searching, out date);
            OrderList = db.Order_Del.Where(s => s.Date_Delived.Value.Year == date.Year &&
            s.Date_Delived.Value.Month == date.Month &&
            s.Date_Delived.Value.Day == date.Day).ToList();
            return OrderList;
        }
    }
}

Flowers_web/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Flowers_web.Models;


namespace Flowers_web.Controllers
{
    public class DeliveryController : Controller
    {
        Delivery model;
        flowersEntities1 db = new flowersEntities1();
        public DeliveryController()
        {
            model =  Delivery.Instance();
        }

        // GET: Delivery
        public ActionResult Index()
        {
            var order = from o in db.Order_Del select o;
            //if (!String.IsNullOrEmpty(searching))
            //{
            //    order = order.Where(s => s.Order_Status.Contains(searching));
            //}
            return View(order.ToList());
        }
        [HttpPost]
        public ActionResult GetOrders(string searching)
        {          
            
            if (!String.IsNullOrEmpty(searching))
            {
                return View("Index",model.GetOrderList(searching));               
            }
            return View();
        }
    }
}

Flowers_web/Views/Delivery/Index.cshtml
@model IEnumerable<Flowers_web.Models.Order_Del>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@using (Html.BeginForm("GetOrders", "Delivery", FormMethod.Post))
{
    @*@Html.TextArea("searching")*@
<input type="date" id="searching" name="searching"  value="@DateTime.Now.ToString("MM/dd/yyyy")"/>
    @*<select class="form-control" id="searching" name="searching">
        <option>OK</option>
        <option>Payed</option>
        <option selected></option>
    </select>
    <select class="form-control" id="searching" name="searching">
        <option>@DateTime.Today</option>
        <option>Payed</option>
        <option selected></option>
    </select>*@
    <input type="submit" value="submit" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Order_Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bouquet_Quontity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Delived)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order_Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size_Bouquets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bouquet.Bouquet_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cust2.Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Driver.Driver_DLicence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Florist.Frorist_Fname)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bouquet_Quontity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Delived)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order_Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total_Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size_Bouquets)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bouquet.Bouquet_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cust2.Fname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Driver.Driver_DLicence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Florist.Frorist_Fname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Order_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.Order_ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Order_ID })
            </td>
        </tr>
    }

</table>